import type { LucideProps } from "lucide-react"
import {
  TrendingUp,
  Sparkles,
  Gauge,
  LayoutGrid,
  Search,
  Globe,
  ShieldCheck,
  FileText,
  Rocket,
  Calendar,
  Phone,
  MonitorSmartphone,
  Megaphone,
  PenTool,
  MapPin,
  BarChart3,
  Check,
  CheckCircle,
  Handshake,
  Target,
  Clock,
  Send,
  CircleAlert,
  LoaderCircle,
  Star,
  Menu,
  Crown,
  Zap,
  ArrowRight,
  Twitter,
  Linkedin,
  X,
  Instagram,
  Download,
  Info,
  MessageCircle,
  Bot,
} from "lucide-react"

const iconProps: LucideProps = {
  strokeWidth: 1.5,
}

export const Icons = {
  TrendingUp: (props: LucideProps) => <TrendingUp {...iconProps} {...props} />,
  Sparkles: (props: LucideProps) => <Sparkles {...iconProps} {...props} />,
  Gauge: (props: LucideProps) => <Gauge {...iconProps} {...props} />,
  LayoutGrid: (props: LucideProps) => <LayoutGrid {...iconProps} {...props} />,
  Search: (props: LucideProps) => <Search {...iconProps} {...props} />,
  Globe: (props: LucideProps) => <Globe {...iconProps} {...props} />,
  ShieldCheck: (props: LucideProps) => <ShieldCheck {...iconProps} {...props} />,
  FileText: (props: LucideProps) => <FileText {...iconProps} {...props} />,
  Rocket: (props: LucideProps) => <Rocket {...iconProps} {...props} />,
  Calendar: (props: LucideProps) => <Calendar {...iconProps} {...props} />,
  Phone: (props: LucideProps) => <Phone {...iconProps} {...props} />,
  MonitorSmartphone: (props: LucideProps) => <MonitorSmartphone {...iconProps} {...props} />,
  Megaphone: (props: LucideProps) => <Megaphone {...iconProps} {...props} />,
  PenTool: (props: LucideProps) => <PenTool {...iconProps} {...props} />,
  MapPin: (props: LucideProps) => <MapPin {...iconProps} {...props} />,
  BarChart3: (props: LucideProps) => <BarChart3 {...iconProps} {...props} />,
  Check: (props: LucideProps) => <Check {...iconProps} {...props} />,
  CheckCircle: (props: LucideProps) => <CheckCircle {...iconProps} {...props} />,
  Handshake: (props: LucideProps) => <Handshake {...iconProps} {...props} />,
  Target: (props: LucideProps) => <Target {...iconProps} {...props} />,
  Clock: (props: LucideProps) => <Clock {...iconProps} {...props} />,
  Send: (props: LucideProps) => <Send {...iconProps} {...props} />,
  CircleAlert: (props: LucideProps) => <CircleAlert {...iconProps} {...props} />,
  LoaderCircle: (props: LucideProps) => <LoaderCircle {...iconProps} {...props} />,
  Star: (props: LucideProps) => <Star {...iconProps} {...props} />,
  Menu: (props: LucideProps) => <Menu {...iconProps} {...props} />,
  X: (props: LucideProps) => <X {...iconProps} {...props} />,
  Crown: (props: LucideProps) => <Crown {...iconProps} {...props} />,
  Zap: (props: LucideProps) => <Zap {...iconProps} {...props} />,
  ArrowRight: (props: LucideProps) => <ArrowRight {...iconProps} {...props} />,
  Twitter: (props: LucideProps) => <Twitter {...iconProps} {...props} />,
  Linkedin: (props: LucideProps) => <Linkedin {...iconProps} {...props} />,
  Instagram: (props: LucideProps) => <Instagram {...iconProps} {...props} />,
  Download: (props: LucideProps) => <Download {...iconProps} {...props} />,
  Info: (props: LucideProps) => <Info {...iconProps} {...props} />,
  MessageCircle: (props: LucideProps) => <MessageCircle {...iconProps} {...props} />,
  Bot: (props: LucideProps) => <Bot {...iconProps} {...props} />,
}
